### ISSUE TITLE
SELECT ... FOR UPDATE runs on slaves resulting in: WordPress database error The MySQL server is running with the --read-only option so it cannot execute this statement for query

### ISSUE THREAD

**Issue by archon810** [stuttter/ludicrousdb#55]
Hi @JJJ @spacedmonkey,

It looks like ludicrousdb isn't routing SELECT ... FOR UPDATE to the master db, because if it runs on a slave (which is set to readonly on purpose), the query fails as follows:

`[31-Jan-2018 13:32:15 UTC] WordPress database error The MySQL server is running with the --read-only option so it cannot execute this statement for query
                SELECT * FROM BLA
                WHERE object_id = 1234
                AND type = 'FOO' FOR UPDATE; made by ...`

The SELECT logic in ldb probably thinks it's OK to send all queries to slaves, which doesn't seem to be the case.

**Comment by diditho** [comment]
I have the same issue, my slave is receivibf update query

**Comment by archon810** [comment]
@spacedmonkey Any chance you could look at this next? Thanks.

**Comment by spacedmonkey** [comment]
Having a very very quick look into this, I think the issue is this line - https://github.com/stuttter/ludicrousdb/blob/master/ludicrousdb/includes/class-ludicrousdb.php#L1364 . It is looking for UPDATE in the query but not checking for "FOR UPDATE". This syntax was new to me and new to mysql, so this edge case was never consided. I will try and get some time on this in the coming weeks.

**Comment by archon810** [comment]
cc @sebsz

**Comment by takotakot** [comment]
> Having a very very quick look into this, I think the issue is this line - https://github.com/stuttter/ludicrousdb/blob/master/ludicrousdb/includes/class-ludicrousdb.php#L1364 . It is looking for UPDATE in the query but not checking for "FOR UPDATE". This syntax was new to me and new to mysql, so this edge case was never consided. I will try and get some time on this in the coming weeks.

@spacedmonkey I think read/write is determined in the function `is_write_query( $q )`: 
https://github.com/stuttter/ludicrousdb/blob/d5d27fc4e19ccfeecac627130e1ec68a800ca381/ludicrousdb/includes/class-ludicrousdb.php#L348-L353
noted:

> Quick and dirty: only SELECT statements are considered read-only.

@archon810 `if(preg_match( '/^(?:UPDATE)\s/i', $q )) return true;` may work (not tested).

**Comment by takotakot** [comment]
@archon810 Could you please check with https://github.com/takotakot/ludicrousdb/tree/refine_is_write_query ?

**Comment by JJJ** [comment]
PR merged. This should be fixed. Please reopen if not. 👍

**Comment by ooxif** [comment]
This did not fix the problem due to the trailing `\s` in the regex pattern.

The function returns a false when the query does not have a trailing space.
`is_write_query('SELECT * FROM table WHERE id = 1 FOR UPDATE')` => false

Queries w/ a trailing space get a true.
`is_write_query('SELECT * FROM table WHERE id = 1 FOR UPDATE ')` => true

I patched the code only for the `SELECT ... FOR UPDATE` statement.
This should minimize unwanted effects, moreover, it's simple.
https://github.com/ooxif/ludicrousdb/commit/65c2f896e44205fc467ab75c820a552f68837a88

**Comment by takotakot** [comment]
@ooxif I'm very sorry that I didn't care much about corner cases. (Because that was WIP for me...)
I've made a patch to fix trailing space problem. It is only a patch. Your approach may be better. Thanks!

**Comment by desmeit** [comment]
I have the same problem with wordpress.
I installed it as described here: 
https://sternerstuffdesign.com/2019/02/wordpress-auto-scaling-aws-rds-aurora/

The error in Query Monitor if I click on "plugins":
```
UPDATE `wp_options`
SET `option_value` = '1588857562'
WHERE `option_name` = '_transient_timeout_plugin_slugs'

The MySQL server is running with the --read-only option so it cannot execute this statement
```

I tried it with a master / slave configuration:

```
$wpdb->add_database(array(
    'host'     => DB_HOST, // Use the RDS cluster write endpoint here
    'user'     => DB_USER,
    'password' => DB_PASSWORD,
    'name'     => DB_NAME,
    'write'    => 1, // master can write
    'read'     => !defined('DB_HOST_RPL1') ? 1 : 0, // master only reads if no replica is configured

));

if(defined('DB_HOST_RPL1')):
    $wpdb->add_database(array(
        'host'     => DB_HOST_RPL1, // Read endpoint here
        'user'     => DB_USER,
        'password' => DB_PASSWORD,
        'name'     => DB_NAME,
        'write'    => 0,
        'read'     => 1,
    ));
endif;
```

I took the endpoint of the cluster for writer (DB_HOST) and reader (DB_HOST_RPL1').
What I'm doing wrong?
